package com.example.demo

import runtime.domain.command.Command
import runtime.domain.command.CommandContext
import runtime.domain.command.CommandParameter
import runtime.domain.command.CommandResult
import runtime.domain.obj.ObjectRef
import runtime.domain.obj.ObjectId
import runtime.domain.script.EntityModelScript

/**
 * Template-based CRUD commands over the Task model, generated by [EntityModelScript].
 * Registers as `taskcreate` / `taskupdate` / `taskdelete` / `taskvalidate`.
 */
object TaskScript : EntityModelScript<Task>(TASK_TYPE, namePrefix = "task") {

    override fun createModel(params: Any?): Task {
        val p = params as? Map<*, *> ?: error("Missing parameters")
        val title = p["title"] as? String ?: error("Missing title")
        val status = p["status"] as? String ?: "open"
        return Task(title = title, status = status)
    }

    override fun updateModel(existing: Task, params: Any?): Task {
        val p = params as? Map<*, *> ?: error("Missing parameters")
        val title = p["title"] as? String ?: error("Missing title")
        return existing.copy(title = title, status = p["status"] as? String ?: existing.status)
    }

    override fun validate(model: Task): String? =
        if (model.title.isBlank()) "Title must not be blank" else null
}

class CreateTaskCommand : Command(
    "create",
    "Create a task",
    "Tasks",
    parameters = listOf(
        CommandParameter("title", "string", required = true, description = "Task title"),
        CommandParameter("boardId", "uuid", required = false, description = "Id of the parent board")
    )
) {
    override suspend fun executeInternal(context: CommandContext, params: Any?): CommandResult {
        val p = params as? Map<*, *> ?: return CommandResult.error("Missing parameters")
        val title = p["title"] as? String ?: return CommandResult.error("Missing title")
        return context.withProjectLock {
            val boardRef = when (val boardIdStr = p["boardId"] as? String) {
                null -> null
                else -> {
                    val boardId = runCatching { ObjectId(java.util.UUID.fromString(boardIdStr)) }.getOrNull()
                        ?: return@withProjectLock CommandResult.error("Invalid boardId: $boardIdStr")
                    val board = context.getObject<Board>(BOARD_TYPE, boardId)
                        ?: return@withProjectLock CommandResult.error("Board not found")
                    ObjectRef(BOARD_TYPE, boardId)
                }
            }
            val task = Task(title = title, status = "open", board = boardRef)
            val ref = context.objectList<Task>(TASK_TYPE).create(task)
            val references = listOfNotNull(ref, boardRef)
            CommandResult.success(value = task, references = references)
        }
    }
}

class ListTasksCommand : Command(
    "list",
    "List tasks",
    "Tasks",
    parameters = listOf(CommandParameter("boardId", "uuid", required = false, description = "Filter by board"))
) {
    override suspend fun executeInternal(context: CommandContext, params: Any?): CommandResult {
        val p = params as? Map<*, *>
        val boardId = p?.get("boardId") as? String
        val parsedBoard = boardId?.let {
            runCatching { ObjectId(java.util.UUID.fromString(it)) }.getOrNull()
        }
        if (boardId != null && parsedBoard == null) {
            return CommandResult.error("Invalid boardId: $boardId")
        }
        val list = context.objectList<Task>(TASK_TYPE)
        val rows = list.list().mapNotNull { ref ->
            val task = list.get(ref.objectId) ?: return@mapNotNull null
            if (parsedBoard != null && task.board?.objectId != parsedBoard) return@mapNotNull null
            mapOf(
                "id" to ref.objectId.value.toString(),
                "title" to task.title,
                "status" to task.status,
                "boardId" to task.board?.objectId?.value?.toString(),
                "order" to task.order
            )
        }.sortedBy { (it["order"] as? Number)?.toInt() ?: 0 }
        return CommandResult.success(value = rows)
    }
}

class ReorderTasksCommand : Command(
    "reordertasks",
    "Persist a new task order",
    "Tasks",
    parameters = listOf(CommandParameter("ids", "array<string>", required = true, description = "Task ids in the new order"))
) {
    override suspend fun executeInternal(context: CommandContext, params: Any?): CommandResult {
        val p = params as? Map<*, *> ?: return CommandResult.error("Missing parameters")
        val ids = (p["ids"] as? List<*>)?.filterIsInstance<String>()
            ?: return CommandResult.error("Missing ids list")
        return context.withProjectLock {
            val list = context.objectList<Task>(TASK_TYPE)
            val affected = mutableListOf<ObjectRef>()
            ids.forEachIndexed { index, id ->
                val objectId = runCatching { ObjectId(java.util.UUID.fromString(id)) }.getOrNull()
                    ?: return@forEachIndexed
                val current = list.get(objectId) ?: return@forEachIndexed
                if (current.order != index) {
                    list.update(objectId, current.copy(order = index))
                    affected += ObjectRef(TASK_TYPE, objectId)
                }
            }
            CommandResult.success(value = mapOf("reordered" to affected.size), references = affected)
        }
    }
}

class CompleteTaskCommand : Command(
    "complete",
    "Mark a task as done",
    "Tasks",
    parameters = listOf(CommandParameter("id", "uuid", required = true, description = "Task id"))
) {
    override suspend fun executeInternal(context: CommandContext, params: Any?): CommandResult {
        val p = params as? Map<*, *> ?: return CommandResult.error("Missing parameters")
        val id = parseId(p) ?: return CommandResult.error("Missing or invalid id")
        return context.withProjectLock {
            val list = context.objectList<Task>(TASK_TYPE)
            val current = list.get(id) ?: return@withProjectLock CommandResult.error("Task not found")
            val updated = current.copy(status = "done")
            list.update(id, updated)
            CommandResult.success(
                value = updated,
                references = listOf(ObjectRef(TASK_TYPE, id))
            )
        }
    }
}

class DeleteTaskCommand : Command(
    "delete",
    "Delete a task",
    "Tasks",
    parameters = listOf(CommandParameter("id", "uuid", required = true, description = "Task id"))
) {
    override suspend fun executeInternal(context: CommandContext, params: Any?): CommandResult {
        val p = params as? Map<*, *> ?: return CommandResult.error("Missing parameters")
        val id = parseId(p) ?: return CommandResult.error("Missing or invalid id")
        return context.withProjectLock {
            val list = context.objectList<Task>(TASK_TYPE)
            if (!list.delete(id)) {
                return@withProjectLock CommandResult.error("Task not found")
            }
            CommandResult.success(value = mapOf("deleted" to id.value.toString()))
        }
    }
}

/** V6 demo: model-bound action — reopens a task (disabledWhen status=open). */
class ReopenTaskCommand : Command(
    "reopentask",
    "Reopen a completed task",
    "Tasks",
    parameters = listOf(CommandParameter("id", "uuid", required = true, description = "Task id"))
) {
    override suspend fun executeInternal(context: CommandContext, params: Any?): CommandResult {
        val p = params as? Map<*, *> ?: return CommandResult.error("Missing parameters")
        val id = parseId(p) ?: return CommandResult.error("Missing or invalid id")
        return context.withProjectLock {
            val list = context.objectList<Task>(TASK_TYPE)
            val current = list.get(id) ?: return@withProjectLock CommandResult.error("Task not found")
            if (current.status != "done") {
                return@withProjectLock CommandResult.error("Only completed tasks can be reopened")
            }
            val updated = current.copy(status = "open")
            list.update(id, updated)
            CommandResult.success(value = updated, references = listOf(ObjectRef(TASK_TYPE, id)))
        }
    }
}

class TaskStatsCommand : Command("stats", "Task statistics", "Tasks") {
    override suspend fun executeInternal(context: CommandContext, params: Any?): CommandResult {
        val tasks = context.objectList<Task>(TASK_TYPE).values()
        val done = tasks.count { it.status == "done" }
        return CommandResult.success(
            value = mapOf(
                "total" to tasks.size,
                "open" to tasks.count { it.status == "open" },
                "done" to done,
                "donePercent" to if (tasks.isEmpty()) 0 else done * 100 / tasks.size
            )
        )
    }
}
